apiVersion: v1
kind: ConfigMap
metadata:
  name: online-app-body
data:
  # property-like keys; each key maps to a simple value
  body: "<html><title>Second app</title><body><div>I'm the app 1.23.2!</div></body></html>"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: online-deployment
  labels:
    app: online-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: online-nginx
  template:
    metadata:
      labels:
        app: online-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.23.2
        ports:
        - containerPort: 80
        volumeMounts:
        - name: app-body
          mountPath: /usr/share/nginx/html
          readOnly: true
      
      volumes:
      - name: app-body
        configMap:
          name: online-app-body
          items:
          - key: "body"
            path: "index.html"