apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:nabladev/unlimited-poc.git
    targetRevision: HEAD
    path: online
    chart: online
    targetRevision: 1.0.0
    # chart: sealed-secrets
    # repoURL: https://bitnami-labs.github.io/sealed-secrets
    # targetRevision: 1.16.1
    helm:
      releaseName: online-release
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kubeseal