{{- range $name, $tenant := .Values.tenants }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}-online-app-body
  namespace: {{ $name }}
data:
  body: "<html><title>Second app</title><body><div>I'm the app 1.23.2!</div></body></html>"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}-online-deployment
  namespace: {{ $name }}
  labels:
    app: {{ $name }}-online-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ $name }}-online-nginx
  template:
    metadata:
      labels:
        app: {{ $name }}-online-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.23.2
        ports:
        - containerPort: 80
        volumeMounts:
        - name: app-body
          mountPath: /usr/share/nginx/html
          readOnly: true
        # Standard healthcheck
        livenessProbe:
          httpGet:
            path: /
            port: 80
            httpHeaders:
            - name: Custom-Header
              value: CustomHeaderInCaseWeNeedIt
          initialDelaySeconds: 3
          periodSeconds: 3
        # Delay the execution of every other probe, until this one becomes healthy
        # Useful if an app is slow to startup
        startupProbe:
          httpGet:
            path: /
            port: 80
          failureThreshold: 30
          periodSeconds: 10 # 10 * 30 = 600s before the livenessProbe kicks in
      
      volumes:
      - name: app-body
        configMap:
          name: {{ $name }}-online-app-body
          items:
          - key: "body"
            path: "index.html"
---
{{- end}}