{{- range $name, $tenant := .Values.tenants }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $name }}-online-deployment-hpa
  namespace: {{ $name }}
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: {{ $name }}-online-deployment
  targetCPUUtilizationPercentage: 80
---
{{- end}}