{{- range $name, $tenant := .Values.tenants }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}-online-svc
  namespace: {{ $name }}
spec:
  selector:
    app: {{ $name }}-online-nginx
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 80
---
{{- end }}